#!/bin/sh
# ============================================================================
# init.sh — one-time project bootstrap (compose-envkit).
#
#   sh init.sh        (or ./init.sh)
#
# Generated by install.sh and NEVER clobbered — this copy is yours to customize.
# It is the project-agnostic STARTING POINT for "set this repo up on a fresh
# machine":
#
#   1. Seed real env files from the committed example.* templates (never
#      overwrites an existing file).
#   2. Fan out to each immediate subproject's own init.sh, if present.
#   3. Your project-specific steps (build assets, mkdir data dirs, …).
#
# Deliberately POSIX sh and side-effect-light: NO sudo, NO chmod 777, NO secrets
# written anywhere. Re-runnable (idempotent).
# ============================================================================

set -eu

# Run from this script's own directory (the project root).
cd "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

say() { printf '%s\n' "$*"; }

# --- 1. Seed real env files from example.* (never clobber) -------------------
# example.env -> .env, example.dev.env -> .dev.env, example.secrets.env ->
# .secrets.env, … Fill in the real values afterwards (secrets stay gitignored).
say "init: seeding env files from example.*"
for _ex in example.*; do
  [ -e "$_ex" ] || continue            # no example.* present => glob stayed literal
  _target=".${_ex#example.}"
  if [ -e "$_target" ]; then
    say "  exists  $_target"
  else
    cp "$_ex" "$_target"
    say "  created $_target  (from $_ex)"
  fi
done

# --- 2. Fan out to subproject init scripts ----------------------------------
# Runs <subdir>/init.sh for every immediate subdirectory that ships one — this is
# how a monorepo root sets up each subproject (build extensions/themes, mkdir
# data dirs, …) without the kit needing to know any service names.
for _d in */; do
  [ -d "$_d" ] || continue             # no subdirs => glob stayed literal
  if [ -f "$_d/init.sh" ] && [ -x "$_d/init.sh" ]; then
    say "init: -> ${_d}init.sh"
    ( cd "$_d" && ./init.sh )
  fi
done

# --- 3. Project-specific setup (add yours below) ----------------------------
# All optional, all portable — no sudo, no chmod 777. Examples:
#
#   mkdir -p data                       # data dirs your compose mounts
#   ./docker compose build              # prebuild images
#
# Hide local edits to COMMITTED demo env files from `git status` so tweaking them
# locally doesn't show as a change. Opt-in and git-guarded (no-ops outside a git
# work tree). NEVER mark a real .secrets.env this way.
assume_unchanged() {  # assume_unchanged <path>...
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0
  for _f in "$@"; do
    [ -e "$_f" ] && git update-index --assume-unchanged "$_f" 2>/dev/null || true
  done
}
# assume_unchanged .dev.env

say "init: done."
